version: "3.9"

services:
  backend:
    build:
      context: ./application/backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5002:5002"
    env_file:
      - ./application/backend/.env
    restart: always

  frontend:
    build:
      context: ./application/frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "9000:80"  
    env_file:
      - ./application/frontend/.env
    depends_on:
      - backend
    restart: always
