apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: image-video-gallery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shrinidhiupadhyaya/image-video-backend:v1.0.38
          ports:
            - containerPort: 5002
          envFrom:
            - secretRef:
                name: backend-secrets
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: image-video-gallery
spec:
  selector:
    app: backend
  ports:
    - port: 5002
      targetPort: 5002
      nodePort: 30502
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: image-video-gallery
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: image-video-gallery
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: backend
