apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: image-video-gallery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: shrinidhiupadhyaya/image-video-backend:latest
        ports:
        - containerPort: 5002
        envFrom:
        - secretRef:
            name: backend-secrets
        - configMapRef:
            name: backend-config
        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 5
          periodSeconds: 10
