apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: image-video-gallery-ingress
  namespace: image-video-gallery
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: gallery.shrinidhi.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5002
